Update h5py because otherwise the build fails
...
    /tmp/pip-install-07e4n5qh/h5py_95256cbcb05a4a278f12d0a23cafc383/h5py/defs.c:34665:15: error: too few arguments to function ‘H5Sencode2’
    34665 |   __pyx_t_1 = H5Sencode(__pyx_v_obj_id, __pyx_v_buf, __pyx_v_nalloc); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 3303, __pyx_L1_error)
          |               ^~~~~~~~~
    In file included from /usr/include/hdf5.h:38,
                     from /tmp/pip-install-07e4n5qh/h5py_95256cbcb05a4a278f12d0a23cafc383/h5py/api_compat.h:27,
                     from /tmp/pip-install-07e4n5qh/h5py_95256cbcb05a4a278f12d0a23cafc383/h5py/defs.c:790:
    /usr/include/H5Spublic.h:373:15: note: declared here
      373 | H5_DLL herr_t H5Sencode2(hid_t obj_id, void *buf, size_t *nalloc, hid_t fapl);
          |               ^~~~~~~~~~
    error: command '/usr/bin/gcc' failed with exit code 1

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>